# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee0fe3b58f356f0b1c32a45dbeb256111d9c806278bdec74745ff89bdb4a12f96fad68f89b4d4f5bf822b8d12903e66bccc56b2fb5909843a0626f82f83e57f4

test:
  secret_key_base: e38ba883e0d491c8125f98ac9d01250cefc5d846562211407d7ad80797f2d7b390b5a43427dd0fe65ab7ac849432ed6adad54cee9a914b538b9d12f833240e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
